### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by mhadam**
Converts the project to a Go module and more importantly fixes problems with connection pooling (under load there were excess TIME_WAIT connections).

### CODE REVIEW

**Comment by jbeemster** [comment]
Hey @mhadam - looks like you updated the copyright in the README but not in any of the actual golang files - for consistency might not be a bad idea to update those aswell!

Have you also updated the documentation with the new changes?

**Comment by jrluis** [comment]
LGTM!

**Comment by mhadam** [comment]
Should be good now @jbeemster

**Comment by jbeemster** [comment]
LGTM!

**Pull request merged**
